# config for training standard slot attention on slipscape image sequences with 4 objects
type = "slotmachine"

[model]
obs_width    = 64
obs_height   = 64
feature_size = 64
slot_size    = 64
mlp_size     = 64
latent_size  = 5
seq_length   = 4
action_size  = 0
dynamics     = false

[slot]
sa_iterations = 3
num_slots     = 5

[train]
batch_size = 64
epochs     = 250
log_rate   = 1
ckpt_rate  = 50
recon_loss = true
dis_loss   = false
recon_w    = 1

[train.opt]
lr = 2e-4
wd = 1e-2
